// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSxN_Fv4a18zBv_9_LabBgN4TnCURUqqY',
    appId: '1:815079937857:web:3a5a4bdec8f1503cc573c0',
    messagingSenderId: '815079937857',
    projectId: 'chatbot1045',
    authDomain: 'chatbot1045.firebaseapp.com',
    storageBucket: 'chatbot1045.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbP7Ds2Yqnhfl1tuTrlCUmAOGLz8WD-U',
    appId: '1:815079937857:android:3aa065b597ad45e1c573c0',
    messagingSenderId: '815079937857',
    projectId: 'chatbot1045',
    storageBucket: 'chatbot1045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxbras_PGroXVC80wI__BpWGKhoX1YfEY',
    appId: '1:815079937857:ios:f2b2a1bd0bc47c39c573c0',
    messagingSenderId: '815079937857',
    projectId: 'chatbot1045',
    storageBucket: 'chatbot1045.firebasestorage.app',
    iosBundleId: 'com.example.da',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxbras_PGroXVC80wI__BpWGKhoX1YfEY',
    appId: '1:815079937857:ios:f2b2a1bd0bc47c39c573c0',
    messagingSenderId: '815079937857',
    projectId: 'chatbot1045',
    storageBucket: 'chatbot1045.firebasestorage.app',
    iosBundleId: 'com.example.da',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSxN_Fv4a18zBv_9_LabBgN4TnCURUqqY',
    appId: '1:815079937857:web:ceda6e88dd140741c573c0',
    messagingSenderId: '815079937857',
    projectId: 'chatbot1045',
    authDomain: 'chatbot1045.firebaseapp.com',
    storageBucket: 'chatbot1045.firebasestorage.app',
  );
}
